[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/mold", "-Zshare-generics=y", "-Zthreads=12"]

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
rustflags = ["-Zthreads=12"]

[profile.dev]
opt-level = 0
debug = 2
incremental = true
codegen-units = 1024

[net]
git-fetch-with-cli=true
